# This workflow will build the extension and upload an artifact
name: Build and upload extension

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends make gettext gnome-shell libglib2.0-bin

    - name: Build the extension bundle
      run: |
        make build

    - name: Run checks on extension
      run: |
        make check

    - uses: actions/upload-artifact@v3
      with:
        name: AlphabeticalAppGrid@stuarthayhurst.shell-extension.zip
        path: build/AlphabeticalAppGrid@stuarthayhurst.shell-extension.zip
